In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('EstudiantesConvertido.csv')

In [4]:
df

    Nombre  Edad Genero       Carrera Semestre
0   Victor    28      M     Auditoria  Primero
1   Josefa    23      F   Informatica  Primero
2     Raul    26      M       Derecho   Quinto
3  Mariana    27      F   Informatica  Septimo
4  Rodrigo    22      M       Derecho  Tercero
5  Gustavo    25      M  Arquitectura  Septimo
6     Lucy    23      F   Informatica  Primero
7    Sofia    24      F      Economia   Noveno

In [5]:
df.iloc[1,3]

'Informatica'

In [6]:
df.iloc[2,:3]

Nombre    Raul
Edad        26
Genero       M
Name: 2, dtype: object

In [8]:
df.loc[1,'Edad']

23

In [9]:
df.loc[:3,('Carrera','Nombre')]

       Carrera   Nombre
0    Auditoria   Victor
1  Informatica   Josefa
2      Derecho     Raul
3  Informatica  Mariana

In [10]:
df.iloc[1, :3]

Nombre    Josefa
Edad          23
Genero         F
Name: 1, dtype: object

In [12]:
df['TURNO'] = pd.Series(['tarde','noche','tarde','noche','noche','tarde'])

In [13]:
df

    Nombre  Edad Genero       Carrera Semestre  TURNO
0   Victor    28      M     Auditoria  Primero  tarde
1   Josefa    23      F   Informatica  Primero  noche
2     Raul    26      M       Derecho   Quinto  tarde
3  Mariana    27      F   Informatica  Septimo  noche
4  Rodrigo    22      M       Derecho  Tercero  noche
5  Gustavo    25      M  Arquitectura  Septimo  tarde
6     Lucy    23      F   Informatica  Primero    NaN
7    Sofia    24      F      Economia   Noveno    NaN

In [14]:
Semestre = df.pop('Semestre')

In [15]:
df

    Nombre  Edad Genero       Carrera  TURNO
0   Victor    28      M     Auditoria  tarde
1   Josefa    23      F   Informatica  noche
2     Raul    26      M       Derecho  tarde
3  Mariana    27      F   Informatica  noche
4  Rodrigo    22      M       Derecho  noche
5  Gustavo    25      M  Arquitectura  tarde
6     Lucy    23      F   Informatica    NaN
7    Sofia    24      F      Economia    NaN

In [22]:
df=df.append(pd.Series(['Carlos',27,'M','Sociologia','tarde'],
index=['Nombre','Edad','Genero','Carrera','TURNO']),ignore_index=True)

C:\Users\andos\AppData\Local\Temp\ipykernel_20600\2919810845.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(pd.Series(['Carlos',27,'M','Sociologia','tarde'],

In [20]:
df = df[df['Nombre'] != 'Carlos']

In [23]:
df

    Nombre  Edad Genero       Carrera  TURNO Turno
0   Victor    28      M     Auditoria  tarde   NaN
1   Josefa    23      F   Informatica  noche   NaN
2     Raul    26      M       Derecho  tarde   NaN
3  Mariana    27      F   Informatica  noche   NaN
4  Rodrigo    22      M       Derecho  noche   NaN
5  Gustavo    25      M  Arquitectura  tarde   NaN
6     Lucy    23      F   Informatica    NaN   NaN
7    Sofia    24      F      Economia    NaN   NaN
8   Carlos    27      M    Sociologia  tarde   NaN

In [24]:
df = df.drop(columns = ['Turno'])

In [25]:
df

    Nombre  Edad Genero       Carrera  TURNO
0   Victor    28      M     Auditoria  tarde
1   Josefa    23      F   Informatica  noche
2     Raul    26      M       Derecho  tarde
3  Mariana    27      F   Informatica  noche
4  Rodrigo    22      M       Derecho  noche
5  Gustavo    25      M  Arquitectura  tarde
6     Lucy    23      F   Informatica    NaN
7    Sofia    24      F      Economia    NaN
8   Carlos    27      M    Sociologia  tarde

In [26]:
df.drop([1,2])

    Nombre  Edad Genero       Carrera  TURNO
0   Victor    28      M     Auditoria  tarde
3  Mariana    27      F   Informatica  noche
4  Rodrigo    22      M       Derecho  noche
5  Gustavo    25      M  Arquitectura  tarde
6     Lucy    23      F   Informatica    NaN
7    Sofia    24      F      Economia    NaN
8   Carlos    27      M    Sociologia  tarde

In [27]:
df[(df['Genero']=='F') & (df['Edad'] >= 22)]

    Nombre  Edad Genero      Carrera  TURNO
1   Josefa    23      F  Informatica  noche
3  Mariana    27      F  Informatica  noche
6     Lucy    23      F  Informatica    NaN
7    Sofia    24      F     Economia    NaN

In [28]:
df

    Nombre  Edad Genero       Carrera  TURNO
0   Victor    28      M     Auditoria  tarde
1   Josefa    23      F   Informatica  noche
2     Raul    26      M       Derecho  tarde
3  Mariana    27      F   Informatica  noche
4  Rodrigo    22      M       Derecho  noche
5  Gustavo    25      M  Arquitectura  tarde
6     Lucy    23      F   Informatica    NaN
7    Sofia    24      F      Economia    NaN
8   Carlos    27      M    Sociologia  tarde

In [29]:
df.sort_values('Carrera')

    Nombre  Edad Genero       Carrera  TURNO
5  Gustavo    25      M  Arquitectura  tarde
0   Victor    28      M     Auditoria  tarde
2     Raul    26      M       Derecho  tarde
4  Rodrigo    22      M       Derecho  noche
7    Sofia    24      F      Economia    NaN
1   Josefa    23      F   Informatica  noche
3  Mariana    27      F   Informatica  noche
6     Lucy    23      F   Informatica    NaN
8   Carlos    27      M    Sociologia  tarde

In [30]:
df.sort_values('Edad')

    Nombre  Edad Genero       Carrera  TURNO
4  Rodrigo    22      M       Derecho  noche
1   Josefa    23      F   Informatica  noche
6     Lucy    23      F   Informatica    NaN
7    Sofia    24      F      Economia    NaN
5  Gustavo    25      M  Arquitectura  tarde
2     Raul    26      M       Derecho  tarde
3  Mariana    27      F   Informatica  noche
8   Carlos    27      M    Sociologia  tarde
0   Victor    28      M     Auditoria  tarde

In [31]:
df.dropna()

    Nombre  Edad Genero       Carrera  TURNO
0   Victor    28      M     Auditoria  tarde
1   Josefa    23      F   Informatica  noche
2     Raul    26      M       Derecho  tarde
3  Mariana    27      F   Informatica  noche
4  Rodrigo    22      M       Derecho  noche
5  Gustavo    25      M  Arquitectura  tarde
8   Carlos    27      M    Sociologia  tarde