In [1]:
import pandas as pd

In [4]:
DF1 = pd.DataFrame({'Autos':['Nissan','Ford','Audi'],
'Color':['Blanco','Azul','Rojo']})

In [10]:
DF2 = pd.DataFrame({'Autos':['Toyota','Ford','Audi'],
'Modelo':['2018','2020','2022']})

In [15]:
DF=pd.merge(DF1,DF2, on='Autos', how='right')

In [7]:
DF

    Autos   Color Modelo
0  Nissan  Blanco   2018
1    Ford    Azul   2020
2    Audi    Rojo   2022

In [16]:
DF

    Autos Color Modelo
0  Toyota   NaN   2018
1    Ford  Azul   2020
2    Audi  Rojo   2022