In [1]:
import pandas as pd

In [7]:
DF1 = pd.DataFrame({'Autos':['Nissan','Ford','Audi'],
'Color':['Blanco','Azul','Rojo']}).set_index('Autos')

In [6]:
DF2 = pd.DataFrame({'Autos':['Nissan','Ford','Audi'],
'Modelo':['2018','2020','2022']}).set_index('Autos')

In [9]:
DF1

         Color
Autos
Nissan  Blanco
Ford      Azul
Audi      Rojo

In [8]:
DF2

       Modelo
Autos
Nissan   2018
Ford     2020
Audi     2022

In [10]:
DF=pd.concat([DF1,DF2],axis=1)

In [11]:
DF

         Color Modelo
Autos
Nissan  Blanco   2018
Ford      Azul   2020
Audi      Rojo   2022