In [1]:
import pandas as pd

In [4]:
DF1 = pd.DataFrame({'Nombre':['Jose','Max'],
'Carreras':['Economia','Arquitectura'],
'Edad':[23,26]}).set_index('Nombre')

In [5]:
DF2 = pd.DataFrame({'Nombre':['Aurora','Maria'],
'Carreras':['Medicina','Informatica'],
'Edad':[22,28]}).set_index('Nombre')

In [6]:
DF=pd.concat([DF1,DF2])

In [7]:
DF1

            Carreras  Edad
Nombre
Jose        Economia    23
Max     Arquitectura    26

In [8]:
DF2

           Carreras  Edad
Nombre
Aurora     Medicina    22
Maria   Informatica    28

In [9]:
DF

            Carreras  Edad
Nombre
Jose        Economia    23
Max     Arquitectura    26
Aurora      Medicina    22
Maria    Informatica    28